export const BLUR_DELAY = 0.04;

export const DATA = {
  personalData: {
    name: "Jean de Dieu HAGENIMANA",
    description:
      "I am a Frontend Developer. I love to learn and explore new technologies and am passionate about problem-solving. I love to do most of the things using TypeScript.",
    skill: [
      "Javascript",
      "php",
      "Python",
      "TypeScript",
      "Node.js",
      "React.js",
      "Next.js",
      "Django",
      "Laravel",
      "Zustand",
      "PostgreSQL",
      "MySQL",
      "Express.js",
      "MongoDB",
      "Docker",
      "Prisma",
    ],
    email: "jdhagena77@gmail.com",
    phone: "+250784239311",
    link: [
      {
        name: "github",
        url: "https://github.com/jeandedieuH",
      },
      {
        name: "linkedin",
        url: "https://www.linkedin.com/in/jeandedieuH",
      },
    ],
    resume: "/CV.pdf",
    aboutMe: `I'm a passionate Full-Stack Developer with a love for coding, learning, and exploring the latest in web technologies, I specialize in creating robust, scalable applications using the MERN, PERN stacks and other modern technologies like Next.js, vue.js and nuxt.js.`,
  },
  educations: [
    {
      id: 1,
      year: "2020-2024",
      title: "Master of Computer Applications (MCA)",
      school: "Noida Institute Of Engineering And Technology,Greater Noida",
      location: "UP. Greater Noida",
      field: "Computer Application",
    },
    {
      id: 2,
      year: "2017 - 2020",
      title: "Bachelor of Science (B.Sc IT)",
      school: "Anand Vishwa Gurukul Sr. Night College Thane West Maharashtr",
      location: "Thane, Maharashtra",
      field: "Information Technology",
    },
  ],
  experiences: [
    {
      company: "Emarsun Technology",
      role: "Full Stack Developer",
      startDate: "Nov 2024",
      endDate: "Jan 2025",
      location: "Thane, IN",
      technologies: [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Express.js",
        "Mongodb",
        "Shadcn UI",
        "Zustand",
      ],
    },
    {
      company: "Weingenious Technocrats Private Ltd",
      role: "Frontend Developer",
      startDate: "Nov 2022",
      endDate: "Oct 2024",
      location: "Surat, IN",
      technologies: [
        "React.js",
        "Next.js",
        "Tailwind CSS",
        "Redux",
        "Zustand",
        "Material UI",
        "Git",
        "CI/CD",
        "Graphql",
      ],
    },
    {
      company: "Cloud Analogy Private Ltd",
      role: "Salesforce developer Intern",
      startDate: "Feb 2022",
      endDate: "Apr 2022",
      location: "Noida, IN",
      technologies: ["Java", "Apex lightning", "SOQL"],
    },
  ],
  projectData: [
    {
      name: "Prestige Learning",
      title: "Prestige Learning",
      results: [
        { title: "This is a collection of re-usable components." },
        { title: "You can copy and paste into your web apps." },
      ],
      link: "https://www.prestigelearning.net/",
      code: "",
      image: "/project/shapexui.png",
      tools: [
        "Next.js",
        "Framer Motion",
        "Tailwind CSS",
        "Shadcn/ui",
        "Appwrite",
        "PostgreSQL",
      ],
      role: "Full Stack Developer",
    },
    {
      name: "Kwiga Bibiliya",
      title: "Kwiga Bibiliya",
      results: [
        { title: "Developed an AI-powered debate platform." },
        {
          title:
            "Debate summaries with performance scores, resource recommendations,",
        },
      ],
      link: "https://kwigabibiliya.com/",
      code: "",
      image: "/project/debate.png",
      tools: ["NextJs 15", "MongoDB(Prisma ORM)", "AuthJs"],
      role: "Full Stack Developer",
    },
    {
      name: "Noter",
      title: "Notion clone.",
      results: [
        { title: "Noter serves as the collaborative workspace." },
        { title: "Where enhanced and more efficient work takes place." },
      ],
      link: "https://noter-steel.vercel.app/",
      code: "https://github.com/yogesh2104/noter",
      image: "/project/noter.png",
      tools: ["NextJs", "ConvexDB", "Clerk Auth"],
      role: "Full Stack Developer",
    },
    {
      name: "PromptForAi",
      title: "Discover & Share AI Prompts.",
      results: [
        { title: "Discover AI Prompt and Share AI" },
        { title: "Create new prompt" },
        { title: "Also you can Search other people prompt" },
      ],
      link: "https://prompt-for-ai.vercel.app/",
      image: "/project/promtForAi.png",
      tools: ["NextJs", "MongoDB", "NextAuth"],
      role: "Full Stack Developer",
      code: "https://github.com/yogesh2104/promptForAI",
    },
    {
      name: "Smart Health Advisor",
      title: "Predicts Diseases Based On Symptoms",
      results: [
        { title: "Discover AI Prompt and Share AI" },
        { title: "Create new prompt" },
        { title: "Also you can Search other people prompt" },
      ],
      link: "https://smart-health-advisor.vercel.app/",
      image: "/project/health.png",
      tools: ["NextJs", "Shadcn UI", "Django", "Python"],
      role: "Frontend Developer",
      code: "https://github.com/saurabhsharma104/Smart-Health-Advisor",
    },
    {
      name: "Coding InterView",
      title: "Coding-Interview-University Repo.",
      results: [
        { title: "This is simple static web page" },
        {
          title:
            "Simplified version of coding-interview-university github repo.",
        },
      ],
      link: "https://yogesh2104.github.io/CodingInterView/",
      image: "/project/iViewer.png",
      tools: ["HTML", "CSS", "Javascript", "Bootstrap"],
      role: "Frontend Developer",
      code: "https://github.com/yogesh2104/CodingInterView",
    },
    {
      name: "ThreeJs Diamond",
      title: "ThreeJs Diamond Customizer.",
      results: [
        { title: "This is 3D Dimaond Renderer." },
        { title: "Allow to change ring and diamond color" },
      ],
      link: "https://threejsdesign.vercel.app/",
      image: "/project/threejs.png",
      tools: ["Nextjs", "Javascript", "ThreeJS", "Zustand", "Tailwind CSS"],
      role: "Frontend Developer",
      code: null,
    },
  ],
};
