export const BLUR_DELAY = 0.04;

export const DATA = {
  personalData: {
    name: "Jean de Dieu HAGENIMANA",
    description:
      "I'm a passionate Full-Stack Developer with a love for coding, learning, and exploring the latest in web technologies, I specialize in creating robust, scalable applications using the MERN, PERN stacks and other modern technologies like Next.js, vue.js and nuxt.js.",
    skill: [
      "Javascript",
      "Php",
      "Python",
      "TypeScript",
      "Node.js",
      "React.js",
      "Next.js",
      "Django",
      "Laravel",
      "Zustand",
      "PostgreSQL",
      "MySQL",
      "Express.js",
      "MongoDB",
      "Docker",
      "Prisma",
      "Wordpress",
      "Tailwind CSS",
    ],
    email: "jdhagena77@gmail.com",
    phone: "+250784239311",
    link: [
      {
        name: "github",
        url: "https://github.com/jeandedieuH",
      },
      {
        name: "linkedin",
        url: "https://www.linkedin.com/in/jeandedieuH",
      },
    ],
    resume: "/CV.pdf",
    aboutMe: `I'm a passionate Full-Stack Developer with a love for coding, learning, and exploring the latest in web technologies, I specialize in creating robust, scalable applications using the MERN, PERN stacks and other modern technologies like Next.js, vue.js and nuxt.js.`,
  },
  educations: [
    {
      id: 1,
      year: "2009-2011",
      title: "High School Certificate",
      school: "Ecole des Sciences de Musanze",
      location: "Musanze, Rwanda",
      field: "Mathematics-Physics-Chemistry",
    },
    {
      id: 2,
      year: "2013-2017",
      title: "Bachelor’s Degree in Civil Engineering",
      school: "University of Rwanda-College of Science and Technology",
      location: "Kigali, Rwanda",
      field: "Civil engineering",
    },
  ],
  experiences: [
    {
      company: "Self-employed",
      role: "Full Stack Developer",
      startDate: "Feb 2024",
      endDate: "Present",
      location: "Kigali, Rwanda",
      technologies: [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Express.js",
        "Shadcn UI",
        "Zustand",
        "Node.js",
        "Appwrite",
        "PostgreSQL",
      ],
    },
  ],
  projectData: [
    {
      name: "LMS Platform",
      title: "Prestige Learning",
      results: [
        {
          title:
            "A full featured lms platform with course creation, filtering, commenting and more.",
        },
        {
          title:
            "Role based access control for admin, users, students and instructors",
        },

        { title: "Course purchase and subscription." },
      ],
      link: "https://prestigelearning.net/",
      code: "",
      image: "/project/prestige-learning.png",
      tools: [
        "Next.js",
        "TypeScript",
        "Framer Motion",
        "Tailwind CSS",
        "Shadcn/ui",
        "Appwrite",
        "PostgreSQL",
        "shadcn/ui",
        "Tailwind CSS",
        "Prisma",
      ],
      role: "Full Stack Developer",
    },
    {
      name: "Bible study",
      title: "Kwiga Bibiliya",
      results: [
        { title: "Best bible study app in Kinyarwanda" },
        {
          title:
            "A Bible study app with full features like verse navigation and search, video portal, blog and more.",
        },
      ],
      link: "https://kwigabibiliya.com/",
      code: "",
      image: "/project/kwiga-bibiliya.png",
      tools: [
        "Next.js",
        "TypeScript",
        "React.js",
        "Framer Motion",
        "Tailwind CSS",
        "Shadcn/ui",
        "Appwrite",
        "PostgreSQL",
        "shadcn/ui",
        "Tailwind CSS",
      ],
      role: "Full Stack Developer",
    },
    {
      name: "Job search",
      title: "Jobify.",
      results: [
        { title: "Custom authentication and authorization." },
        { title: "Job search and filtering." },
        { title: "Ability to create, edit and delete jobs." },
      ],
      link: "https://jobify.jdhagena.com/",
      code: "https://github.com/jeandedieuH/mern-jobify",
      image: "/project/jobify.jpg",
      tools: [
        "Node.js",
        "React.js",
        "Express.js",
        "MongoDB",
        "TanStack Query",
        "react-router",
        "Styled components",
      ],
      role: "Full Stack Developer",
    },
    {
      name: "Social Media",
      title: "Snapgram",
      results: [
        { title: "Authentication and authorization" },
        { title: "Ability to create, edit and delete posts" },
        { title: "Ability to add comments and replies on posts" },
        { title: "Ability to upload images" },
        { title: "Ability to view other users profile" },
        { title: "Ability to like and unlike posts" },
      ],
      link: "https://snapgram.jdhagena.com/",
      image: "/project/snapgram.jpg",
      tools: [
        "React.js",
        "Tailwind CSS",
        "Appwrite",
        "TypeScript",
        "React Query",
        "Shadcn",
      ],
      role: "Full Stack Developer",
      code: "https://github.com/jeandedieuH/snapgram",
    },
  ],
};
